class TestBuildingSingleForcastingModelFromEpisode:
    def setup(self):
        self._forcaster_model_trainer = ...
        self._forcaster_model_architecture = ...
        self._forcaster_model_training_architecture = ...
        self._learning_episodes = []
        self._testing_episodes = []