from typing import Optional, Any

from nd_robotic.robot.structure.kind.body.nervous.neuron.action_potential.group.group import Group as ActionPotentialGroup
from nd_robotic.robot.structure.kind.mind.cognition.process.kind.memory.composite.trace.interface import Interface as TraceInterface
from nd_robotic.robot.structure.kind.mind.cognition.process.kind.memory.composite.trace.kind.core.kind import Kind as TraceKind


class Trace(TraceInterface):
    """
    - This class is bridge between formatted data in form of a Dic and a group of ActionPotentials, so if you give it one, it should be abale to return back the other
        - it can be used as training pair between action potentioal group and formatted data
    internal or external stimuli (such as seeing a train or high blood pressure) has a neural coding representation for a piece of information.
    this is a hyposthesis dicussed here https://en.wikipedia.org/wiki/Efficient_coding_hypothesis
    - trace is the connection between body's nervous system and mind. on one hand it receives potential activity fieelds and on theother hand it converts it to a nested action_potential_group point such as a dictionary or a composite pattern
    - This is a lost in time memory cellgaller
    An role or a sensor read happens
    - the smalleast action_potential_group part of the momery being generated by action_potentials population field
    - this is the boundry between body brain and mind mind
    - action_potentials can not be decorated or be composite or decorated
    - trace covers from action_potential activit field to structed action_potential_group
    - this is the leaf of composite pattern
    """

    def __init__(self, formatted_data:Optional[Any], action_potential_group: Optional[ActionPotentialGroup] , name: Optional[str]):
        """

        Args:
            action_potential_group:
            name:
        """
        self._population_activity_field = action_potential_group
        # it is just a point, a action_potential_group point, without a population it has no meaning
        self._formatted_data: Any = None

        # is it a command? a lidar sensor? a initial_mission? This must be guessed from formatted action_potential_group
        self._kind: Optional[Any] = None
        # is what is given from population
        self._name = name

    @classmethod
    def init_from_formatted_data_and_kind_and_name(cls, formatted_data: Any, kind: TraceKind, name: Optional[str]) -> "Trace":
        this_object = cls(formatted_data, None, name)
        this_object._kind = kind
        return this_object

    def get_formatted_data(self) -> Any:
        return self._formatted_data

    def get_nervous_population_activity_field(self) -> Optional[ActionPotentialGroup]:
        return self._population_activity_field

    def get_kind(self) -> TraceKind:
        if self._kind is None:
            self._kind = self.extract_kind()
        return self._kind

    def set_name(self, name: Optional[str]):
        """
        This can be set from a population such as a trace action_potential_group
        Args:
            name:

        Returns:

        """
        self._name = name

    def extract_kind(self) -> TraceKind:
        """"""
        pass
