from nd_robotic.robot.robot import Level0
from nd_robotic.robot.robot import Level0
from nd_robotic.robot.robot import Level2
from nd_robotic.robot.robot import Level3
from nd_robotic.robot.robot import Level4
from nd_robotic.robot.robot import Level_5
from typing import List

class Levels:
    """
    - TODO: All levels of awareness need to be reviewed as they are all generated by GPT
    """
    def __init__(self):
        self._memebers = List[Level0, Level1, Level2, Level3, Level4, Level_5]

    def get_memebers(self)->List[Level]:
        return self._memebers
